import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import FixedFooter from "./components/FixedFooter";

import { CartProvider } from "./cartProvider";

export const metadata = {
  title: "Codeswear",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CartProvider>
          <Navbar />
          {children}
          <Footer />
          <FixedFooter />
        </CartProvider>
      </body>
    </html>
  );
}
